In [1]:
# Name : Diksha Divasaliwala
# Reg No: 24-27-18
# Programme: M.tech. Data Science
# Assignment Number: 2


## Q1. 

In [9]:
# a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape

In [11]:
import numpy as np
var1 = np.arange(31)
print(var1)
print("Shape :", var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape : (31,)


In [13]:
# b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. 

In [15]:
var2 = np.delete(var1,0).reshape(6,-1)
print(var2)
print("Shape: ",var2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Shape:  (6, 5)


In [17]:
# c)Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape.

In [19]:
var3 = np.delete(var1,0).reshape(2, 3, -1)
print(var3)
print("Shape: ",var3.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
Shape:  (2, 3, 5)


In [21]:
# d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3.

In [23]:
var2[1, 0] = -1
print("After Modification")
print("var2:\n", var2)
print("var1:\n", var1)
print("var3:\n", var3)


After Modification
var2:
 [[ 1  2  3  4  5]
 [-1  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
var1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [25]:
# Explanation: on modifying var2, the data in var1 will also be modified since var2 is just a different view of var1.
# As var1 changes, var3 also changes as it is a reshaped view of var1.
# This is because reshape returns a view.So, change in one will affect the others.

In [29]:
# e)Figure out how the NumPy sum function works (and the axis argument in particular) 
# and do the following:
# (i) Sum var3 over its second dimension and print the result.
# (ii) Sum var3 over its third dimension and print the result.
# (iii) Sum var3 over both its first and third dimensions and print the result.


In [31]:
sum1 = np.sum(var3, axis=1)
print("Sum over the second dimension:\n", sum1)

sum2 = np.sum(var3, axis=2)
print("Sum over the third dimension:\n", sum2)

sum02 = np.sum(var3, axis=(0, 2))
print("Sum over the first and third dimensions:\n", sum02)

Sum over the second dimension:
 [[18 21 24 27 30]
 [63 66 69 72 75]]
Sum over the third dimension:
 [[ 15  40  65]
 [ 90 115 140]]
Sum over the first and third dimensions:
 [105 155 205]


In [33]:
# f)Write code to do the following:
# (i) Slice out the second row of var2 and print it.
# (ii) Slice out the last column of var2 using the -1 notation and print it.
# (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [39]:
row = var2[1, :]
print("Second row of var2:\n", row)
last_col = var2[:,-1:]
print("Last column of var2:\n", last_col)
matrix = var2[0:2,-2:]
print("Top right 2x2 submatrix of var2: \n", matrix)

Second row of var2:
 [-1  7  8  9 10]
Last column of var2:
 [[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]]
Top right 2x2 submatrix of var2: 
 [[ 4  5]
 [ 9 10]]


## Q2

In [41]:
# a)create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [43]:
vector = np.arange(10) + 1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
# b)Now, create a 10 × 10 matrix A in which Aij = i + j.

In [47]:
i = vector.reshape(10, 1)  
j = vector.reshape(1, 10)  
A = i + j
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [49]:
# c) First, create a fake “data set” with 50 examples, each with five dimensions.

In [51]:
import numpy.random as npr
data = np.exp(npr.randn(50,5))

In [53]:
# d)generating a 50 × 5 matrix of standard normal random variates and exponentiate them.

In [55]:
print(data.shape)

(50, 5)


In [57]:
print(data)

[[ 1.20047487  0.09464808  1.42686448  1.07896525  3.033373  ]
 [ 0.12805465  6.89441242  0.4848892   3.18667602  0.94801315]
 [ 0.53043324  2.0905249   0.30277299  2.63110273  0.17561804]
 [ 0.10223285  1.85527284  0.17103201  0.76346315  0.841075  ]
 [ 0.49291054  4.07096179  0.55588008  2.03623513  0.51165414]
 [ 0.24643095  0.81282719  2.61217041  0.43279819  0.5946666 ]
 [ 1.40399443  0.06996214  1.21744394  1.64344755  1.87884814]
 [ 1.39560202  1.11723614  1.40288289  0.32082927  0.18879495]
 [ 3.38960068  0.83513985  2.96796439  0.73313107  1.82300326]
 [ 1.40856014  0.77842879  0.16086434  0.10651219  4.36106993]
 [ 1.6019852   4.07108733  0.54703232  0.63562507  2.47595559]
 [ 3.66980131  1.22396769  1.54672686  1.50302029  1.83525338]
 [ 0.89061429  0.90972839  3.09562148  0.39219119  0.47006708]
 [ 0.95761804  0.83321592  3.42852531  3.68834599  0.28376027]
 [ 2.64574157  0.90378658  0.92414718  0.93536866  0.50957268]
 [ 3.6535588   0.64508716  0.1498565   0.49843079  0.83

In [59]:
# e) compute the mean and standard deviation of each column.
#Store these vectors into variables and print both of them.

In [61]:
mean = data.mean(axis=0)
std = data.std(axis=0)
print("Mean of each col:", mean)
print("Standard deviation of each col:", std)

Mean of each col: [1.61613012 1.6031985  1.31548685 1.4520015  1.51901838]
Standard deviation of each col: [1.55104765 1.82088958 1.01748994 1.39366168 2.36076908]


In [63]:
# f) Now standardize the data matrix by 1) subtracting the mean off of each column, 
#and 2) dividing each column by its standard deviation. Do this via broadcasting, 
#and store the result in a matrix called normalized. To verify that you successfully 
#did it, compute the mean and standard deviation of
#the columns of normalized and print them out

In [65]:
std_data = (data - mean) / std
print("Mean:\n", std_data.mean(axis=0))
print("Standard deviation:", std_data.std(axis=0))

Mean:
 [ 2.44249065e-17  1.42108547e-16  0.00000000e+00  2.99760217e-16
 -2.01227923e-16]
Standard deviation: [1. 1. 1. 1. 1.]


## Q3

In [67]:
# a) o write a function that will produce a Vandermonde matrix for a 
# vector [1, 2, . . . ,N]T for any N. Do it without using a loop.
# Use your function for N = 12, store it in variable named vander, and print the result.

In [87]:
import numpy as np
def vandermonde(N):
    vec = np.arange(N) + 1
    powers = np.arange(N)
    return vec[:, np.newaxis] ** powers

N = 12
vander = vandermonde(N)
print("12x12 Vandermonde matrix:")
print(vander)

12x12 Vandermonde matrix:
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
      

In [89]:
# b) Now, let’s make a pretend linear system problem with this matrix. Create a vector 
# of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of 
# vander with the vector you just created and store that in a new vector and call it b. 
# Print the vector b.

In [95]:
x = np.ones(N) 
b = np.dot(vander, x)
print("Vector b:\n", b)

Vector b:
 [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [97]:
# c)# First, solve the linear system the naïve way, pretending like you don’t know x. 
# Import numpy.linalg, invert V and multiply it by b. Print out your result. What 
# should you get for your answer? If the answer is different than what you 
# expected, write a sentence about that difference

In [99]:
# Naive approach
from numpy.linalg import inv
inverse = inv(vander)
naive = np.dot(inverse, b)
print("Solution :\n", naive)

Solution :
 [0.99365711 1.00758362 0.99868774 1.00006294 0.99999857 1.00000048
 0.99999993 1.         1.         1.         1.         1.        ]


In [101]:
# Expectation : I expected an ans of vector x close to ones i.e [1 1 1 . .] 
# Difference : However, the output deviated slightly from the expected vector of ones when the naive approach was used.

In [103]:
# d)Now, solve the same linear system using solve. Print out the result. 
# Does it seem more or less in line with what you’d expect?


In [105]:
# Using solve
from numpy.linalg import solve
solve = solve(vander, b)
print("Solution :\n", solve)

Solution :
 [0.99998827 1.00002951 0.99997139 1.00001427 0.99999595 1.00000068
 0.99999993 1.         1.         1.         1.         1.        ]


In [107]:
# Using 'solve' gave a more accurate result which is close to the original vector x

In [113]:
#Github link: https://github.com/Diksha2608/Diksha_24-27-18/blob/main/Assn2_Diksha_Divasaliwala_24-27-18.ipynb

